### ISSUE TITLE
switch-miniupnpc not found

### ISSUE THREAD

**Issue by artemisoftnian** [Stary2001/godot#10]
**Godot version:**

**OS/device including version:**

**Issue description:**

Hi, I'm trying to compile your version of godot switch. But I'm stuck at the point where miniupnpc its used.  As I don't find switch-miniupnpc package anywhere available, I try to compile the package myself from your git repository, but the compilation always fails cause incompatible versions of the package.  Can You point me what repository if any is used to get the correct miniupnpc version needed to compile?.  Can you make available the correct package?  Thanks in advance.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Stary2001** [comment]
whoops, i forgot to upstream it when i was doing actual development
submitted a PR @ https://github.com/devkitPro/pacman-packages/pull/109 but it'll take a bit to get merged
if you're not using upnp just revert commit 64c319a
sorry about the delay, i've been kinda busy lately

**Comment by Stary2001** [comment]
package is available via pacman now, closing
