### ISSUE TITLE
Problem compiling Export Template for Switch

### ISSUE THREAD

**Issue by noraexplora** [Stary2001/godot#11]
**When I attempt to compile the 3.1.1-stable_switch-export branch of your repo using this command:**

scons platform=switch tools=no target=release bits=64

**I get the following output:**

scons: Reading SConscript files ...
OSError: [Errno 2] No such file or directory:
  File "/home/nora/godot/SConstruct", line 321:
    detect.configure(env)
  File "./platform/switch/detect.py", line 162:
    bullet_version = subprocess.check_output(['aarch64-none-elf-pkg-config', 'bullet', '--modversion']).strip()
  File "/usr/lib/python2.7/subprocess.py", line 216:
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394:
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047:
    raise child_exception

**I hope you can resolve this**

**Comment by Stary2001** [comment]
see https://blog.9net.org/2019/10/godot/ for precompiled templates - also this is caused by not having `switch-pkg-config` installed
