### ISSUE TITLE
How to create an .nro file to port over to the Switch?

### ISSUE THREAD

**Issue by nmattela** [Stary2001/godot#12]
Hey, apologies if this isn't the place to ask such questions, but...
I managed to build this fork of godot, and I exported a random test game I grabbed from the templates section to a .pck file. Now, since I'm new to godot and porting games to the Switch, I'm not so sure what to do at this point; how to I create a binary (I presume an .nro file) to export to my Switch? I got devkitpro and all installed on my Ubuntu machine.
Thanks :)

**Comment by Stary2001** [comment]
You should be able to use the .sh scripts in the root of the repo to build a NRO (or just `scons platform=switch target=release -j8`) when you have all the packages in the README installed.
Then you can place the NRO next to the .pck on the SD and it should pick up the game - hope this helps!

I still need to polish all the export stuff, but for that I need a final release... etc, and I haven't had much time lately

**Comment by MikeTheSnowman** [comment]
> You should be able to use the .sh scripts in the root of the repo to build a NRO (or just `scons platform=switch target=release -j8`) when you have all the packages in the README installed.
> Then you can place the NRO next to the .pck on the SD and it should pick up the game - hope this helps!
> 
> I still need to polish all the export stuff, but for that I need a final release... etc, and I haven't had much time lately

One more thing to add.
When you create your NRO and PCK files, you can rename the files to whatever you want, but they **do** need to have the same name. (Example: pizza.nro & pizza.pck. Or myGame.nro & myGame.pck).

If you don't do this, then when you try to launch godot, you'll only see a black screen before being returned to the homebrew menu.
