### ISSUE TITLE
python 2.7 - TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by MikeTheSnowman** [Stary2001/godot#13]
https://github.com/Stary2001/godot/blob/5f1adeb6ce271baa0c8f49c476d9aae5338938db/platform/switch/detect.py#L168

OS: Ubuntu 18.04.3 (bionic) LTS
Python: 2.7.15+

When using trying to compile I get the following error:
```
user0@localhost:~/Downloads/godot-3.1.1-stable_switch$ ./go.sh 
scons: Reading SConscript files ...
TypeError: __init__() got an unexpected keyword argument 'encoding':
  File "/home/kubeuser0/Downloads/godot-3.1.1-stable_switch/SConstruct", line 321:
    detect.configure(env)
  File "./platform/switch/detect.py", line 168:
    bullet_version = subprocess.check_output(['aarch64-none-elf-pkg-config', 'bullet', '--modversion'], encoding='utf-8').strip()
  File "/usr/lib/python2.7/subprocess.py", line 216:
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
```

Looking at the (python 2.7) docs for subprocess.check_output() reveals that it has no named argument called encoding. Removing that argument allows the compile to complete successfully when using python 2.7.

Please note, that this does not have to be done if using python 3.6 or newer.
https://docs.python.org/3/library/subprocess.html#subprocess.check_output

**Comment by nmattela** [comment]
Go to platform/switch/detect.py and remove `encoding='utf-8'` on line 168. Works for me.

**Comment by Stary2001** [comment]
fixed - this https://github.com/godotengine/godot/commit/44f1b390a3604cc141502c76fbf15dd347fc327c needed to be applied to the switch platform as the proper fix
