### ISSUE TITLE
Adding things to the scene makes created .nro crash after godot logo

### ISSUE THREAD

**Issue by rathren** [Stary2001/godot#14]
I managed to build the engine and and a .nro with a empty 3D scene that ran on my switch. But ass soon as I make a little more complex scene (I added a skinned character model as .dae with some .png textures) the .nro just closes back to the switch home screen after the GoDot logo (scene ofc runs fine when pressing play on PC). Is there any list of things that are save to add to the scene or a way to see why the .nro is closing?

**Comment by Stary2001** [comment]
That's odd, nothing I've tried yet has crashed like that - you can send the nro over nxlink to get some log output. (`nxlink -p 'your project name.nro' switch_debug.nro` or so)
Ideally you'd run a debug build to get a proper backtrace of where the crash occurs. If you want to debug this with me you can join the Discord at https://discord.gg/yUC3rUk
